[package]
name = "redix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.4"
mio = { version = "0.8.8", features = ["os-poll", "net"] }
smol = "1.3.0"
